server:
  port: 8001
  servlet:
    context-path: /api


spring:
  application:
    name: samriddhi-social


  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      path: /h2-console
      enable: true
      settings:
        web-allow-others: false

  datasource:
    url: jdbc:h2:file:./../../h2db



#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://18.216.73.188:8761/eureka
#  instance:
#    preferIpAddress: true



user:
  name: Guest

springdoc:
  swagger-ui.path: /swagger